export const CHANNEL_SUCCESS="CHANNEL_SUCCESS";
export const CHANNEL_REQUEST="CHANNEL_REQUEST";
export const CHANNEL_FAILED="CHANNEL_FAILED";

export const SUBSCRIPTION_SUCCESS="SUBSCRIPTION_SUCCESS";
export const SUBSCRIPTION_REQUEST="SUBSCRIPTION_REQUEST";
export const SUBSCRIPTION_FAILED="SUBSCRIPTION_FAILED";

export const REMOVE_SUBSCRIPTION_SUCCESS="REMOVE_SUBSCRIPTION_SUCCESS";
export const REMOVE_SUBSCRIPTION_REQUEST="REMOVE_SUBSCRIPTION_REQUEST";
export const REMOVE_SUBSCRIPTION_FAILED="REMOVE_SUBSCRIPTION_FAILED";

export const ALL_SUBSCRIPTION_SUCCESS="ALL_SUBSCRIPTION_SUCCESS";
export const ALL_SUBSCRIPTION_REQUEST="ALL_SUBSCRIPTION_REQUEST";
export const ALL_SUBSCRIPTION_FAILED="ALL_SUBSCRIPTION_FAILED";
