export const GET_COMMENTS_SUCCESS='GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_FAILED='GET_COMMENTS_FAILED';
export const GET_COMMENTS_REQUEST='GET_COMMENTS_REQUEST';

export const ADD_COMMENTS_SUCCESS='ADD_COMMENTS_SUCCESS';
export const ADD_COMMENTS_FAILED='ADD_COMMENTS_FAILED';

