export const VIDEOS_REQUEST='VIDEOS_REQUEST';
export const VIDEOS_SUCCESS='VIDEOS_SUCCESS';
export const VIDEOS_FAILED='VIDEOS_FAILED';


export const VIDEO_SELECTED_REQUEST='VIDEO_SELECTED_REQUEST';
export const VIDEO_SELECTED_SUCCESS='VIDEO_SELECTED_SUCCESS';
export const VIDEO_SELECTED_FAILED='VIDEO_SELECTED_FAILED';

export const RECOMMENDED_VIDEO_SUCCESS='RECOMMENDED_VIDEO_SUCCESS';
export const RECOMMENDED_VIDEO_REQUEST='RECOMMENDED_VIDEO_REQUEST';
export const RECOMMENDED_VIDEO_FAILED='RECOMMENDED_VIDEO_FAILED';


export const SEARCH_ELEMENT_SUCCESS='SEARCH_ELEMENT_SUCCESS';
export const SEARCH_ELEMENT_REQUEST='SEARCH_ELEMENT_REQUEST';
export const SEARCH_ELEMENT_FAILED='SEARCH_ELEMENT_FAILED';

export const LIKE_VIDEOS_REQUEST='LIKE_VIDEOS_REQUEST';
export const LIKE_VIDEOS_SUCCESS='LIKE_VIDEOS_SUCCESS';
export const LIKE_VIDEOS_FAILED='LIKE_VIDEOS_FAILED';

export const SEARCH_RESULT_SUCCESS='SEARCH_RESULT_SUCCESS';
export const SEARCH_RESULT_REQUEST='SEARCH_RESULT_REQUEST';
export const SEARCH_RESULT_FAILED='SEARCH_RESULT_FAILED';

export const CHANNEL_VIDEO_REQUEST='CHANNEL_VIDEO_REQUEST';
export const CHANNEL_VIDEO_SUCCESS='CHANNEL_VIDEO_SUCCESS';
export const CHANNEL_VIDEO_FAILED='CHANNEL_VIDEO_FAILED';



